name: ChallengePlugin
main: at.mario.challenge.Main
version: 1.0-SNAPSHOT
api-version: 1.21

depend: [CommandAPI]
softdepend: ['Multiverse-Core']

libraries:
  - "de.miraculixx:kpaper:1.1.1"
  - "dev.jorel:commandapi-bukkit-kotlin:9.5.2"