name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Produktions-Verzeichnis via SSH (Password)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /pfad/zum/produktions-verzeichnis
            git pull origin main

      - name: Reload Bukkit Server via Pterodactyl API
        run: |
          curl -X POST "${{ secrets.PTERO_PANEL_URL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/command" \
            -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"command":"bukkit:reload confirm"}'
