name: Deploy to Testserver

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Test-Verzeichnis via SSH (Password)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/lib/pterodactyl/volumes/945744a8-4c1e-4753-918c-a01d9a7f0b48/plugins
            git pull origin development

      - name: Restart Minecraft Test-Server via Pterodactyl API
        run: |
          curl -X POST "${{ secrets.PTERO_PANEL_URL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID_DEV }}/power" \
            -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"signal":"restart"}'
